version: "3.8"
services:
  app:
    image: algertc/alpr-dashboard:latest
    restart: unless-stopped
    ports:
      - "3000:3000" # Change the first port to the port you want to expose
    environment:
      - NODE_ENV=production
      - ADMIN_PASSWORD=password # Change this to a secure password
      - DB_PASSWORD=password # Change this to your postgres password
      - DB_HOST=db:5432 #host:port of your postgres database
      - DB_NAME=postgres
      - DB_USER=postgres
    depends_on:
      - db
