general:
  maxRecords: 2000
  ignoreNonPlate: false
mqtt:
  broker: ''
  topic: alpr/plates
database:
  host: 192.168.1.116:32768
  name: postgres
  user: postgres
  password: password
notifications:
  pushover:
    enabled: true
    app_token: aabingruk9hegm3e1ngh9chzhqp7fc
    user_key: umu78ybrm8jxdnbnz31sba2g2jeayt
    priority: 1
    sound: pushover
    title: ALPR Alert
