general:
  maxRecords: 2000
  ignoreNonPlate: false
mqtt:
  broker: ""
  topic: alpr/plates
database:
  host: localhost:5432
  name: postgres
  user: postgres
  password: password
push:
  server: https://api.pushover.net/1/messages.json
  credentials: null
