general:
  maxRecords: 2000
  ignoreNonPlate: false
mqtt:
  broker: ''
  topic: alpr/plates
database:
  host: 192.168.1.116:32768
  name: postgres
  user: postgres
  password: password
push:
  server: ''
  credentials: ''
