general:
  maxRecords: 2000
  ignoreNonPlate: false
mqtt:
  broker: ""
  topic: alpr/plates
database:
  host: db:5432 #db is the name of the database container in docker and is used as the hostname
  name: postgres
  user: postgres
  password: password
push:
  server: https://api.pushover.net/1/messages.json
  credentials: null
